### ISSUE TITLE
Add OAuth Gen for discord oauth 

### ISSUE THREAD

**Issue by LawMixer** [TreeBen77/discord-oauth2.py#6]
I feel like this is needed for more readability then anything else.

**Comment by treeben77** [comment]
I've added `Client.generate_uri`. It works almost identically to [rblx-open-cloud](https://github.com/TreeBen77/rblx-open-cloud)'s `OAuth2App.generate_uri`, with a few changes:
- `generate_code` param was replaced with `response_type`, and accepts `Literal["code", "token"]` instead of a `bool`.
- The following parameters have been added: `guild_id`, `disable_guild_select`, and `permissions`

It should be added to pip in a few moments

**Comment by zyrafaq** [comment]
For anyone reading this (especially [message above](https://github.com/treeben77/discord-oauth2.py/issues/6#issuecomment-1559319243)) [`Client`](https://github.com/treeben77/discord-oauth2.py/blob/main/discordoauth2/sync_oauth.py#L282).[`generate_uri`](https://github.com/treeben77/discord-oauth2.py/blob/main/discordoauth2/sync_oauth.py#L446) got [another parameter](https://github.com/treeben77/discord-oauth2.py/blob/main/discordoauth2/sync_oauth.py#L451) the `integration_type` which is a [discord param](https://discord.com/developers/docs/resources/application#installation-context) which lets [Discord](https://discord.com) know that you want to install this app as a [user app](https://discord.com/developers/docs/tutorials/developing-a-user-installable-app)/[bot](https://discord.com/developers/docs/topics/oauth2#bot-users).
